package com.testing.component;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import com.testing.util.Util;
public class Qualification {
	WebDriver driver = null;
	Util util = null;
	public Qualification(WebDriver driver) {
		this.driver= driver;
		this.util=new Util(this.driver);
	}
	public void navigate ()throws Exception {
		String qualification="//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-14384']//a[@href='#'][normalize-space()='Qualification']";
		String esolforschools="//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-14575']//a[@href='#'][normalize-space()='ESOL For Schools']";
		String iesol="//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-14575']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-14576']//a[@href='#'][normalize-space()='IESOL']";
		
		
		util.mouseOverClick (qualification,"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//a[normalize-space()='LRN International AS and A Level']");
		util.mouseOverClick ("//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-14384']//a[@href='#'][normalize-space()='Qualification']","//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//a[normalize-space()='LRN International GCSE']");
		util.mouseOverOverClick("//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-14384']//a[@href='#'][normalize-space()='Qualification']",
				"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-14643']//a[@href='#'][normalize-space()='Pre A Foundation']",
				"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//a[contains(text(),'Level 2')]");
		
		util.mouseOverOverClick("//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//a[@href='#'][normalize-space()='Qualification']",
				"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-14567']//a[@href='#'][normalize-space()='Pre U Foundation']", 
				"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-14567']//a[contains(text(),'Level 3')]");
	
		
		//util.mouseOverOverClick(qualification, esolforschools, iesol);
		
		
		util.mouseOverOverOverClick("//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//a[@href='#'][normalize-space()='Qualification']",
				"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-14575']//a[@href='#'][normalize-space()='ESOL For Schools']",
				"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-14575']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-14576']//a[@href='#'][normalize-space()='IESOL']",
				"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-14576']//a[contains(text(),'A1')]");
		
		util.mouseOverOverOverClick("//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//a[@href='#'][normalize-space()='Qualification']",
				"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14575']//a[@href='#'][normalize-space()='ESOL For Schools']",
				"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14575']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-14576']//a[@href='#'][normalize-space()='IESOL']",
				"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-14576']//a[contains(text(),'A2')]");
		
		util.mouseOverOverOverClick("//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//a[@href='#'][normalize-space()='Qualification']",
				"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14575']//a[@href='#'][normalize-space()='ESOL For Schools']",
				"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14575']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-14576']//a[@href='#'][normalize-space()='IESOL']",
				"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-14576']//a[contains(text(),'B1')]");
		
	util.mouseOverOverOverClick("//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//a[@href='#'][normalize-space()='Qualification']",
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14575']//a[@href='#'][normalize-space()='ESOL For Schools']",
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14575']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-14576']//a[@href='#'][normalize-space()='IESOL']", 
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//a[contains(text(),'B2')]");
			
	util.mouseOverOverOverClick("//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//a[@href='#'][normalize-space()='Qualification']",
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14575']//a[@href='#'][normalize-space()='ESOL For Schools']",
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14575']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-14576']//a[@href='#'][normalize-space()='IESOL']", 
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//a[contains(text(),'C1')]");
	
	util.mouseOverOverOverClick("//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//a[@href='#'][normalize-space()='Qualification']",
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14575']//a[@href='#'][normalize-space()='ESOL For Schools']", 
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14575']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-14576']//a[@href='#'][normalize-space()='IESOL']", 
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//a[contains(text(),'C2')]");
	
	util.mouseOverOverOverClick("//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//a[@href='#'][normalize-space()='Qualification']",
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14575']//a[@href='#'][normalize-space()='ESOL For Schools']",
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14575']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-14592']//a[@href='#'][normalize-space()='Communication']", 
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-14592']//a[contains(text(),'A1')]");
	
	util.mouseOverOverOverClick("//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//a[@href='#'][normalize-space()='Qualification']",
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14575']//a[@href='#'][normalize-space()='ESOL For Schools']",
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14575']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-14592']//a[@href='#'][normalize-space()='Communication']",
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-14592']//a[contains(text(),'A2')]");
	
	util.mouseOverOverOverClick("//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//a[@href='#'][normalize-space()='Qualification']",
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14575']//a[@href='#'][normalize-space()='ESOL For Schools']", 
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14575']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-14592']//a[@href='#'][normalize-space()='Communication']", 
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-14592']//a[contains(text(),'A2')]");
	
	util.mouseOverOverOverClick("//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//a[@href='#'][normalize-space()='Qualification']",
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14575']//a[@href='#'][normalize-space()='ESOL For Schools']", 
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14575']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-14592']//a[@href='#'][normalize-space()='Communication']", 
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-14592']//a[contains(text(),'B1')]");

	
	util.mouseOverOverClick("//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//a[@href='#'][normalize-space()='Qualification']",
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-14619']//a[@href='#'][normalize-space()='Teaching English']", 
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//a[contains(text(),'ELTAA')]");
	
	util.mouseOverOverClick("//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//a[@href='#'][normalize-space()='Qualification']", 
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-14619']//a[@href='#'][normalize-space()='Teaching English']", 
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//a[contains(text(),'ELTAB')]");
	
	util.mouseOverOverClick("//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//a[@href='#'][normalize-space()='Qualification']",
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-14619']//a[@href='#'][normalize-space()='Teaching English']",
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//a[contains(text(),'ELTAC')]");
	
	util.mouseOverOverClick("//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//a[@href='#'][normalize-space()='Qualification']",
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-14619']//a[@href='#'][normalize-space()='Teaching English']",
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//a[contains(text(),'ELTAD')]");
	
	util.mouseOverOverClick("//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//a[@href='#'][normalize-space()='Qualification']", 
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-14642']//a[@href='#'][normalize-space()='General Teaching']",
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//a[contains(text(),'ETAB')]");
	
	util.mouseOverOverClick("//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//a[@href='#'][normalize-space()='Qualification']",
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-14642']//a[@href='#'][normalize-space()='General Teaching']",
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//a[contains(text(),'Level 3 Certificate')]");
			
	util.mouseOverOverClick("//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//a[@href='#'][normalize-space()='Qualification']",
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor menu-item-has-children menu-item-14384']//ul[@class='sub-menu']//li[@class='menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-14642']//a[@href='#'][normalize-space()='General Teaching']", 
			"//ul[@class='nav navbar-nav menu-main-menu thim-ekits-menu__nav']//a[contains(text(),'Level 5')]");
	
	}
}
